## Вычисления с помощью Numpy


Задание №1

In [1]:
import numpy as np

In [16]:
a=np.array([[ 1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])


In [17]:
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [18]:
a= a.transpose()

In [19]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [22]:
mean_a= a.mean(axis=0)

In [23]:
mean_a

array([2. , 8.4])

Задание №2

In [26]:
a_centered= a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание №3

In [48]:
a_centered= a_centered.transpose()
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
a_centered_sp

8.0

In [50]:
Cov=a_centered_sp/ (a.shape[0]-1)
Cov

2.0


# Работа с данными в Pandas

Задание №1

In [66]:
import pandas as pd

In [67]:
authors= pd.DataFrame({'author_id':[1, 2, 3], 'author_name':['Тургенев', 'Чехов', 'Островский']})

In [68]:
books = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3] , 
                     'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'] ,
                     'price':[450, 300, 350, 500, 450, 370, 290]})

In [71]:
authors_price= pd.merge(authors, books, on='author_id', how= 'inner' )
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [118]:
top5 = authors_price.sort_values(by='price', ascending=False).head()
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [117]:
authors_stat = pd.DataFrame({'author_name' : authors_price['author_name'].unique(),
                             'min_price' : authors_price.groupby('author_name', sort=False)['price'].min(),
                             'max_price' : authors_price.groupby('author_name', sort=False)['price'].max(),
                             'mean_price' : authors_price.groupby('author_name', sort=False)['price'].mean()})
authors_stat.reset_index(drop= True , inplace= True )
authors_stat

author_name  min_price  max_price  mean_price
0    Тургенев        300        450  366.666667
1       Чехов        450        500  475.000000
2  Островский        290        370  330.000000